 create table ip_address (
       id integer generated by default as identity,
        ip_value varchar(255),
        ip_pool_id integer,
        primary key (id)
    );
    
    create table ip_pool (
       id integer generated by default as identity,
        description varchar(255),
        lower_bound varchar(255),
        total_capacity integer not null,
        upper_bound varchar(255),
        used_capacity integer not null,
        primary key (id)
    );
    
    alter table ip_address 
       add constraint FK2womarilt56ye4i2pfd96n1f7 
       foreign key (ip_pool_id) 
       references ip_pool;